services:
  payment-service:
    build:
      context: .
    image: payment_service_image:1.0
    container_name: payment_service
    ports:
      - "3007:3007"
    networks:
      - payment-net
    depends_on:
      payment-migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3007/api/v1/payments/health', (r) => {if(r.statusCode !== 200) throw new Error()})"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  payment-db:
    image: postgres
    restart: always
    shm_size: 128mb
    networks:
      - payment-net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d payment_db}"]
      interval: 5s
      timeout: 10s
      retries: 5

  payment-migrate:
    build: 
      context: .
      args:
        - NODE_ENV=development
      target: builder
    command: ["npm", "run", "db:push"]
    networks:
      - payment-net
    depends_on:
      payment-db: 
        condition: service_healthy
    
  redis:
    image: redis
    networks:
      - payment-net

networks:
  payment-net:
    driver: bridge
